global using System;
global using System.IO;
global using System.Threading.Tasks;
global using System.Windows;
global using Application    = System.Windows.Application;
global using MessageBox     = System.Windows.MessageBox;
global using Color          = System.Windows.Media.Color;
global using Brushes        = System.Windows.Media.Brushes;
global using FontFamily     = System.Windows.Media.FontFamily;
global using RadioButton    = System.Windows.Controls.RadioButton;
global using CheckBox       = System.Windows.Controls.CheckBox;
global using Button         = System.Windows.Controls.Button;
global using Orientation    = System.Windows.Controls.Orientation;
global using Cursors        = System.Windows.Input.Cursors;
